repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
    -   id: doc8
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "3.2"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: rst-backticks
    -   id: rst-directive-colons
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
    -   id: prettier
        types_or: [javascript, css]
        args:
        -  --trailing-comma=es5
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.39.0
    hooks:
    -   id: eslint
        files: \.js?$
        types: [file]
        args:
        - --fix
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3
        entry: black --target-version=py38
-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0.10.0
    hooks:
      - id: pyproject-fmt
-   repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.2
    hooks:
      - id: validate-pyproject
