language: python
sudo: false
python: 3.5
cache:
  directories:
  - "~/.cache/pip"
env:
  - TOXENV="py27-dj18"
  - TOXENV="py33-dj18"
  - TOXENV="py34-dj18"
  - TOXENV="py27-dj19"
  - TOXENV="py27-dj110"
  - TOXENV="py34-dj19"
  - TOXENV="py34-dj110"
  - TOXENV="py35-dj19"
  - TOXENV="py35-dj110"
  - TOXENV="flake8"
  - TOXENV="isort"
  - TOXENV="readme"
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
