language: python
sudo: false
cache: pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 3.4
      env: TOXENV=py34-dj18
    - python: 2.7
      env: TOXENV=py27-dj19
    - python: 3.4
      env: TOXENV=py34-dj19
    - python: 3.5
      env: TOXENV=py35-dj19
    - python: 2.7
      env: TOXENV=py27-dj110
    - python: 3.4
      env: TOXENV=py34-dj110
    - python: 3.5
      env: TOXENV=py35-dj110
    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.4
      env: TOXENV=py34-dj111
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.4
      env: TOXENV=py34-dj20
    - python: 3.5
      env: TOXENV=py35-dj20
    - python: 3.6
      env: TOXENV=py36-dj20
    - env: TOXENV=flake8
    - env: TOXENV=isort
    - env: TOXENV=readme
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
