language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django>=1.4.0,<1.5.0"
  - DJANGO="Django>=1.5.0,<1.6.0"
  - DJANGO="Django>=1.6.0,<1.7.0"
  - DJANGO="Django>=1.7.0,<1.8.0"
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="Django>=1.4.0,<1.5.0"
    - python: "3.3"
      env: DJANGO="Django>=1.4.0,<1.5.0"
    - python: "3.4"
      env: DJANGO="Django>=1.4.0,<1.5.0"
      
    - python: "2.6"
      env: DJANGO="Django>=1.7.0,<1.8.0"
install:
  - pip install -e .
  - travis_retry pip install $DJANGO django-discover-runner sqlparse
script: make test
