language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
matrix:
  include:
    - python: 3.2
      env: DJANGO_VERSION=1.5.1
    - python: 3.3
      env: DJANGO_VERSION=1.5.1
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: python setup.py test
